// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using ShopApi.Models.Enums;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Text.Json.Serialization;

namespace ShopApi.Models
{
    public partial class User
    {
        public int ID { get; set; }
        [Required]
        public string FirstName { get; set; }
        [Required]
        public string LastName { get; set; }
        [Required]
        public string Password { get; set; }
        [Required]
        public string Email { get; set; }
        public DateTime? DOB { get; set; }
        [Required]
        public UserType UserType { get; set; } 
        public string ProfileImageName { get; set; }
        public Customer Customer { get; set; }
        public Seller Seller { get; set; }
        public SiteManager SiteManager { get; set; }
    }
}